// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cwever/next_batch.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NextBatch struct {
	IdValue uint64 `protobuf:"varint,1,opt,name=idValue,proto3" json:"idValue,omitempty"`
	Address uint64 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount  uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *NextBatch) Reset()         { *m = NextBatch{} }
func (m *NextBatch) String() string { return proto.CompactTextString(m) }
func (*NextBatch) ProtoMessage()    {}
func (*NextBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e779bbb59be3dd, []int{0}
}
func (m *NextBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NextBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NextBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NextBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextBatch.Merge(m, src)
}
func (m *NextBatch) XXX_Size() int {
	return m.Size()
}
func (m *NextBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_NextBatch.DiscardUnknown(m)
}

var xxx_messageInfo_NextBatch proto.InternalMessageInfo

func (m *NextBatch) GetIdValue() uint64 {
	if m != nil {
		return m.IdValue
	}
	return 0
}

func (m *NextBatch) GetAddress() uint64 {
	if m != nil {
		return m.Address
	}
	return 0
}

func (m *NextBatch) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*NextBatch)(nil), "alice.cwever.cwever.NextBatch")
}

func init() { proto.RegisterFile("cwever/next_batch.proto", fileDescriptor_47e779bbb59be3dd) }

var fileDescriptor_47e779bbb59be3dd = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2e, 0x4f, 0x2d,
	0x4b, 0x2d, 0xd2, 0xcf, 0x4b, 0xad, 0x28, 0x89, 0x4f, 0x4a, 0x2c, 0x49, 0xce, 0xd0, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0xcc, 0xc9, 0x4c, 0x4e, 0xd5, 0x83, 0x48, 0x43, 0x29, 0xa5,
	0x70, 0x2e, 0x4e, 0xbf, 0xd4, 0x8a, 0x12, 0x27, 0x90, 0x3a, 0x21, 0x09, 0x2e, 0xf6, 0xcc, 0x94,
	0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x18, 0x17, 0x24, 0x93,
	0x98, 0x92, 0x52, 0x94, 0x5a, 0x5c, 0x2c, 0xc1, 0x04, 0x91, 0x81, 0x72, 0x85, 0xc4, 0xb8, 0xd8,
	0x12, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98, 0xc1, 0x12, 0x50, 0x9e, 0x93, 0xc3, 0x89, 0x47,
	0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85,
	0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xa9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9,
	0x25, 0xe7, 0xe7, 0xea, 0x83, 0x9d, 0xa4, 0x0f, 0x75, 0x71, 0x05, 0x8c, 0x51, 0x52, 0x59, 0x90,
	0x5a, 0x9c, 0xc4, 0x06, 0x76, 0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x65, 0x1e, 0x10,
	0xd1, 0x00, 0x00, 0x00,
}

func (m *NextBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NextBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NextBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintNextBatch(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if m.Address != 0 {
		i = encodeVarintNextBatch(dAtA, i, uint64(m.Address))
		i--
		dAtA[i] = 0x10
	}
	if m.IdValue != 0 {
		i = encodeVarintNextBatch(dAtA, i, uint64(m.IdValue))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNextBatch(dAtA []byte, offset int, v uint64) int {
	offset -= sovNextBatch(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NextBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IdValue != 0 {
		n += 1 + sovNextBatch(uint64(m.IdValue))
	}
	if m.Address != 0 {
		n += 1 + sovNextBatch(uint64(m.Address))
	}
	if m.Amount != 0 {
		n += 1 + sovNextBatch(uint64(m.Amount))
	}
	return n
}

func sovNextBatch(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNextBatch(x uint64) (n int) {
	return sovNextBatch(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NextBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNextBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NextBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NextBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdValue", wireType)
			}
			m.IdValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IdValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			m.Address = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Address |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNextBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNextBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNextBatch(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNextBatch
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNextBatch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNextBatch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNextBatch
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNextBatch
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNextBatch
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNextBatch        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNextBatch          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNextBatch = fmt.Errorf("proto: unexpected end of group")
)
